### PR TITLE
Hide Nginx and Passenger versions

### PR DESCRIPTION
**Pull request by mykola42**
Description and Impact
----------------------
`Nginx` and `Passenger` versions should be hidden.

Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.

QA Plan
-------

### CODE REVIEW

**Comment by anfleene** [comment]
do we not need `passenger_show_version_in_header` in the server block?

**Comment by mykola42** [comment]
@anfleene It looks like it should be in `http` context according to this: https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_show_version_in_header

**Comment by anfleene** [comment]
Ah ok. Why did you remove the server ones?

**Comment by anfleene** [comment]
Oh never mind. You're right since both server blocks are included inside the http block you don't need it. 

Code Review looks good 👍

**Pull request merged**
